// templates/java/react/components/UpdateForm.tsx
import React, {useEffect} from 'react';
import {Form, Input, InputNumber, Modal, Radio} from 'antd';
import {

{
    {
        class_name
    }
}
Vo
}
from
"../data";
import TextArea from "antd/es/input/TextArea";

interface Update {

{
    class_name
}
}
FormProps
{
    open: boolean;
    onCreate: (values: {
    {
        class_name
    }
}
    Vo
) =>
    void;
    onCancel: () => void;
    {
        {
            table_name
        }
    }
    Vo ? : {
    {
        class_name
    }
}
    Vo;
}

const UpdateForm: React.FC<Update
{
    {
        class_name
    }
}
FormProps > = ({open, onCreate, onCancel, userVo}) => {
    const [form] = Form.useForm();
    const FormItem = Form.Item;

    useEffect(() => {
        if (userVo) {
            form.setFieldsValue(userVo);
        }
    }, [open]);

    const handleOk = () => {
        form.validateFields()
            .then((values) => {
                form.resetFields();
                onCreate(values);
            })
            .catch((info) => {
                console.log('Validate Failed:', info);
            });
    }

    const formContent = () => {
        return (
            <>
                {% for column in java_columns %}
                <FormItem
                    label="{{column.column_comment}}"
                    name="{{column.db_name}}"
                    rules={[{required: true, message: '请输入{{column.column_comment}}!'}]}
                >
                    <Input/>
                </FormItem>{% endfor %}

                {/*<FormItem*/}
                {/*    label="排序"*/}
                {/*    name="sort"*/}
                {/*    rules={[{required: true, message: '请输入排序!'}]}>*/}
                {/*    <InputNumber defaultValue={1}/>*/}
                {/*</FormItem>*/}
                {/*<FormItem*/}
                {/*    label="状态"*/}
                {/*    name="status_id"*/}
                {/*    rules={[{required: true, message: '请输入状态!'}]}>*/}
                {/*    <Radio.Group defaultValue={1}>*/}
                {/*        <Radio value={1}>启用</Radio>*/}
                {/*        <Radio value={0}>禁用</Radio>*/}
                {/*    </Radio.Group>*/}
                {/*</FormItem>*/}
                {/*<FormItem*/}
                {/*    label="备注"*/}
                {/*    name="remark"*/}
                {/*>*/}
                {/*    <TextArea rows={2}/>*/}
                {/*</FormItem>*/}
            </>
        )
    }

    const modalFooter = {title: "更新", okText: '保存', onOk: handleOk, onCancel, cancelText: '取消', open, width: 480};
    const formLayout = {labelCol: {span: 7}, wrapperCol: {span: 13}, form};

    return (
        { % raw %
}
    <Modal {...modalFooter} style={{top: 150}}>
        <Form {...formLayout} style={{marginTop: 30}}>
            {formContent()}
        </Form>
    </Modal>
    {%
        endraw %
    }
)
    ;
};

export default UpdateForm;

// templates/java/vue/components/UpdateForm.vue
<template>
  <el-dialog :model-value="dialogUpdateFormVisible" title="更新" style="width: 480px;border-radius: 10px">
    <el-form
        label-width="100px"
        :model="props.record"
        style="max-width: 380px"
        :rules="rules"
    >
      {% for column in java_columns %}
      <el-form-item label="{{column.column_comment}}" prop="{{column.db_name}}">
        <el-input v-model="props.record.{{column.db_name}}"/>
      </el-form-item>
      {% endfor %}
      <!--      <el-form-item label="排序" prop="sort">-->
      <!--        <el-input-number v-model="props.record.sort" :min="1" :max="10"/>-->
      <!--      </el-form-item>-->
      <!--      <el-form-item label="状态" prop="status_id">-->
      <!--        <el-radio-group v-model="props.record.status_id">-->
      <!--          <el-radio :label="1">启用</el-radio>-->
      <!--          <el-radio :label="0">禁用</el-radio>-->
      <!--        </el-radio-group>-->
      <!--      </el-form-item>-->
      <!--      <el-form-item label="备注" prop="remark">-->
      <!--        <el-input v-model="props.record.remark" :rows="2" type="textarea"/>-->
      <!--      </el-form-item>-->
      <el-form-item>
        <el-button type="primary" @click="handleEdit">保存</el-button>
        <el-button @click="handleEditViewClose">取消</el-button>
      </el-form-item>
    </el-form>
  </el-dialog>
</template>

<script lang="ts" setup>

import {reactive, ref} from "vue";
import type {Update

{
  {
    class_name
  }
}
Param
}
from
"@/views/{{table_name}}/data.d";
import type {FormRules} from "element-plus";
import type {IResponse} from "@/api/ajax";
import {update

{
  {
    class_name
  }
}
}
from
"@/views/{{table_name}}/service";

const props = defineProps < {
  record: Update
{
  {
    class_name
  }
}
Param
}>
()

const dialogUpdateFormVisible = ref(false)


const rules = reactive<FormRules>({
{%
  for column in java_columns %}
{
  {
    column.db_name
  }
}
:
[
  {required: true, message: '{{column.column_comment}}不能为空', trigger: 'blur'},
  // {min: 1, max: 5, message: 'Length should be 3 to 5', trigger: 'blur'},
], { % endfor %
}
})


const emit = defineEmits(['handleQuery', 'handleEdit'])

const handleEditViewClose = () => {
  emit("handleEdit");
}

const handleEdit = async () => {
  if (props.record) {
    let addResult: IResponse = await update
    {
      {
        class_name
      }
    }
    (props.record)
    if (addResult.code === 0) {
      dialogUpdateFormVisible.value = false
      emit("handleQuery");
    }
    addResult.code === 0 ? ElMessage.success(addResult.msg) : ElMessage.error(addResult.msg)
  }
}

</script>

<style scoped>

</style>
